apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-ujjh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-ujjh
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-ujjh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-ujjh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-ujjh
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-bcre-tenant/dotnet-component/devfile-sample-dotnet60-basic-ujjh@sha256:9153ad997a775ce97ba747c9437c09ada9a06feef329ab25dac2223ca13a2aa9
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
